
--
-- Data for Name: countries
--
INSERT INTO countries (id, code, name) VALUES (1, 'af', 'Afghanistan');
INSERT INTO countries (id, code, name) VALUES (2, 'ax', 'Åland Islands');
INSERT INTO countries (id, code, name) VALUES (3, 'al', 'Albania');
INSERT INTO countries (id, code, name) VALUES (4, 'dz', 'Algeria');
INSERT INTO countries (id, code, name) VALUES (5, 'as', 'American Samoa');
INSERT INTO countries (id, code, name) VALUES (6, 'ad', 'Andorra');
INSERT INTO countries (id, code, name) VALUES (7, 'ao', 'Angola');
INSERT INTO countries (id, code, name) VALUES (8, 'ai', 'Anguilla');
INSERT INTO countries (id, code, name) VALUES (9, 'aq', 'Antarctica');
INSERT INTO countries (id, code, name) VALUES (10, 'ag', 'Antigua and Barbuda');
INSERT INTO countries (id, code, name) VALUES (11, 'ar', 'Argentina');
INSERT INTO countries (id, code, name) VALUES (12, 'am', 'Armenia');
INSERT INTO countries (id, code, name) VALUES (13, 'aw', 'Aruba');
INSERT INTO countries (id, code, name) VALUES (14, 'au', 'Australia');
INSERT INTO countries (id, code, name) VALUES (15, 'at', 'Austria');
INSERT INTO countries (id, code, name) VALUES (16, 'az', 'Azerbaijan');
INSERT INTO countries (id, code, name) VALUES (17, 'bs', 'Bahamas');
INSERT INTO countries (id, code, name) VALUES (18, 'bh', 'Bahrain');
INSERT INTO countries (id, code, name) VALUES (19, 'bd', 'Bangladesh');
INSERT INTO countries (id, code, name) VALUES (20, 'bb', 'Barbados');
INSERT INTO countries (id, code, name) VALUES (21, 'by', 'Belarus');
INSERT INTO countries (id, code, name) VALUES (22, 'be', 'Belgium');
INSERT INTO countries (id, code, name) VALUES (23, 'bz', 'Belize');
INSERT INTO countries (id, code, name) VALUES (24, 'bj', 'Benin');
INSERT INTO countries (id, code, name) VALUES (25, 'bm', 'Bermuda');
INSERT INTO countries (id, code, name) VALUES (26, 'bt', 'Bhutan');
INSERT INTO countries (id, code, name) VALUES (27, 'bo', 'Bolivia, Plurinational State of');
INSERT INTO countries (id, code, name) VALUES (28, 'bq', 'Bonaire, Sint Eustatius and Saba');
INSERT INTO countries (id, code, name) VALUES (29, 'ba', 'Bosnia and Herzegovina');
INSERT INTO countries (id, code, name) VALUES (30, 'bw', 'Botswana');
INSERT INTO countries (id, code, name) VALUES (31, 'bv', 'Bouvet Island');
INSERT INTO countries (id, code, name) VALUES (32, 'br', 'Brazil');
INSERT INTO countries (id, code, name) VALUES (33, 'io', 'British Indian Ocean Territory');
INSERT INTO countries (id, code, name) VALUES (34, 'bn', 'Brunei Darussalam');
INSERT INTO countries (id, code, name) VALUES (35, 'bg', 'Bulgaria');
INSERT INTO countries (id, code, name) VALUES (36, 'bf', 'Burkina Faso');
INSERT INTO countries (id, code, name) VALUES (37, 'bi', 'Burundi');
INSERT INTO countries (id, code, name) VALUES (38, 'kh', 'Cambodia');
INSERT INTO countries (id, code, name) VALUES (39, 'cm', 'Cameroon');
INSERT INTO countries (id, code, name) VALUES (40, 'ca', 'Canada');
INSERT INTO countries (id, code, name) VALUES (41, 'cv', 'Cape Verde');
INSERT INTO countries (id, code, name) VALUES (42, 'ky', 'Cayman Islands');
INSERT INTO countries (id, code, name) VALUES (43, 'cf', 'Central African Republic');
INSERT INTO countries (id, code, name) VALUES (44, 'td', 'Chad');
INSERT INTO countries (id, code, name) VALUES (45, 'cl', 'Chile');
INSERT INTO countries (id, code, name) VALUES (46, 'cn', 'China');
INSERT INTO countries (id, code, name) VALUES (47, 'cx', 'Christmas Island');
INSERT INTO countries (id, code, name) VALUES (48, 'cc', 'Cocos (Keeling) Islands');
INSERT INTO countries (id, code, name) VALUES (49, 'co', 'Colombia');
INSERT INTO countries (id, code, name) VALUES (50, 'km', 'Comoros');
INSERT INTO countries (id, code, name) VALUES (51, 'cg', 'Congo');
INSERT INTO countries (id, code, name) VALUES (52, 'cd', 'Congo, the Democratic Republic of the');
INSERT INTO countries (id, code, name) VALUES (53, 'ck', 'Cook Islands');
INSERT INTO countries (id, code, name) VALUES (54, 'cr', 'Costa Rica');
INSERT INTO countries (id, code, name) VALUES (55, 'ci', 'Côte d''Ivoire');
INSERT INTO countries (id, code, name) VALUES (56, 'hr', 'Croatia');
INSERT INTO countries (id, code, name) VALUES (57, 'cu', 'Cuba');
INSERT INTO countries (id, code, name) VALUES (58, 'cw', 'Curaçao');
INSERT INTO countries (id, code, name) VALUES (59, 'cy', 'Cyprus');
INSERT INTO countries (id, code, name) VALUES (60, 'cz', 'Czech Republic');
INSERT INTO countries (id, code, name) VALUES (61, 'dk', 'Denmark');
INSERT INTO countries (id, code, name) VALUES (62, 'dj', 'Djibouti');
INSERT INTO countries (id, code, name) VALUES (63, 'dm', 'Dominica');
INSERT INTO countries (id, code, name) VALUES (64, 'do', 'Dominican Republic');
INSERT INTO countries (id, code, name) VALUES (65, 'ec', 'Ecuador');
INSERT INTO countries (id, code, name) VALUES (66, 'eg', 'Egypt');
INSERT INTO countries (id, code, name) VALUES (67, 'sv', 'El Salvador');
INSERT INTO countries (id, code, name) VALUES (68, 'gq', 'Equatorial Guinea');
INSERT INTO countries (id, code, name) VALUES (69, 'er', 'Eritrea');
INSERT INTO countries (id, code, name) VALUES (70, 'ee', 'Estonia');
INSERT INTO countries (id, code, name) VALUES (71, 'et', 'Ethiopia');
INSERT INTO countries (id, code, name) VALUES (72, 'fk', 'Falkland Islands (Malvinas)');
INSERT INTO countries (id, code, name) VALUES (73, 'fo', 'Faroe Islands');
INSERT INTO countries (id, code, name) VALUES (74, 'fj', 'Fiji');
INSERT INTO countries (id, code, name) VALUES (75, 'fi', 'Finland');
INSERT INTO countries (id, code, name) VALUES (76, 'fr', 'France');
INSERT INTO countries (id, code, name) VALUES (77, 'gf', 'French Guiana');
INSERT INTO countries (id, code, name) VALUES (78, 'pf', 'French Polynesia');
INSERT INTO countries (id, code, name) VALUES (79, 'tf', 'French Southern Territories');
INSERT INTO countries (id, code, name) VALUES (80, 'ga', 'Gabon');
INSERT INTO countries (id, code, name) VALUES (81, 'gm', 'Gambia');
INSERT INTO countries (id, code, name) VALUES (82, 'ge', 'Georgia');
INSERT INTO countries (id, code, name) VALUES (83, 'de', 'Germany');
INSERT INTO countries (id, code, name) VALUES (84, 'gh', 'Ghana');
INSERT INTO countries (id, code, name) VALUES (85, 'gi', 'Gibraltar');
INSERT INTO countries (id, code, name) VALUES (86, 'gr', 'Greece');
INSERT INTO countries (id, code, name) VALUES (87, 'gl', 'Greenland');
INSERT INTO countries (id, code, name) VALUES (88, 'gd', 'Grenada');
INSERT INTO countries (id, code, name) VALUES (89, 'gp', 'Guadeloupe');
INSERT INTO countries (id, code, name) VALUES (90, 'gu', 'Guam');
INSERT INTO countries (id, code, name) VALUES (91, 'gt', 'Guatemala');
INSERT INTO countries (id, code, name) VALUES (92, 'gg', 'Guernsey');
INSERT INTO countries (id, code, name) VALUES (93, 'gn', 'Guinea');
INSERT INTO countries (id, code, name) VALUES (94, 'gw', 'Guinea-Bissau');
INSERT INTO countries (id, code, name) VALUES (95, 'gy', 'Guyana');
INSERT INTO countries (id, code, name) VALUES (96, 'ht', 'Haiti');
INSERT INTO countries (id, code, name) VALUES (97, 'hm', 'Heard Island and McDonald Islands');
INSERT INTO countries (id, code, name) VALUES (98, 'va', 'Holy See (Vatican City State)');
INSERT INTO countries (id, code, name) VALUES (99, 'hn', 'Honduras');
INSERT INTO countries (id, code, name) VALUES (100, 'hk', 'Hong Kong');
INSERT INTO countries (id, code, name) VALUES (101, 'hu', 'Hungary');
INSERT INTO countries (id, code, name) VALUES (102, 'is', 'Iceland');
INSERT INTO countries (id, code, name) VALUES (103, 'in', 'India');
INSERT INTO countries (id, code, name) VALUES (104, 'id', 'Indonesia');
INSERT INTO countries (id, code, name) VALUES (105, 'ir', 'Iran, Islamic Republic of');
INSERT INTO countries (id, code, name) VALUES (106, 'iq', 'Iraq');
INSERT INTO countries (id, code, name) VALUES (107, 'ie', 'Ireland');
INSERT INTO countries (id, code, name) VALUES (108, 'im', 'Isle of Man');
INSERT INTO countries (id, code, name) VALUES (109, 'il', 'Israel');
INSERT INTO countries (id, code, name) VALUES (110, 'it', 'Italy');
INSERT INTO countries (id, code, name) VALUES (111, 'jm', 'Jamaica');
INSERT INTO countries (id, code, name) VALUES (112, 'jp', 'Japan');
INSERT INTO countries (id, code, name) VALUES (113, 'je', 'Jersey');
INSERT INTO countries (id, code, name) VALUES (114, 'jo', 'Jordan');
INSERT INTO countries (id, code, name) VALUES (115, 'kz', 'Kazakhstan');
INSERT INTO countries (id, code, name) VALUES (116, 'ke', 'Kenya');
INSERT INTO countries (id, code, name) VALUES (117, 'ki', 'Kiribati');
INSERT INTO countries (id, code, name) VALUES (118, 'kp', 'Korea, Democratic People''s Republic of');
INSERT INTO countries (id, code, name) VALUES (119, 'kr', 'Korea, Republic of');
INSERT INTO countries (id, code, name) VALUES (120, 'kw', 'Kuwait');
INSERT INTO countries (id, code, name) VALUES (121, 'kg', 'Kyrgyzstan');
INSERT INTO countries (id, code, name) VALUES (122, 'la', 'Lao People''s Democratic Republic');
INSERT INTO countries (id, code, name) VALUES (123, 'lv', 'Latvia');
INSERT INTO countries (id, code, name) VALUES (124, 'lb', 'Lebanon');
INSERT INTO countries (id, code, name) VALUES (125, 'ls', 'Lesotho');
INSERT INTO countries (id, code, name) VALUES (126, 'lr', 'Liberia');
INSERT INTO countries (id, code, name) VALUES (127, 'ly', 'Libya');
INSERT INTO countries (id, code, name) VALUES (128, 'li', 'Liechtenstein');
INSERT INTO countries (id, code, name) VALUES (129, 'lt', 'Lithuania');
INSERT INTO countries (id, code, name) VALUES (130, 'lu', 'Luxembourg');
INSERT INTO countries (id, code, name) VALUES (131, 'mo', 'Macao');
INSERT INTO countries (id, code, name) VALUES (132, 'mk', 'Macedonia, the Former Yugoslav Republic of');
INSERT INTO countries (id, code, name) VALUES (133, 'mg', 'Madagascar');
INSERT INTO countries (id, code, name) VALUES (134, 'mw', 'Malawi');
INSERT INTO countries (id, code, name) VALUES (135, 'my', 'Malaysia');
INSERT INTO countries (id, code, name) VALUES (136, 'mv', 'Maldives');
INSERT INTO countries (id, code, name) VALUES (137, 'ml', 'Mali');
INSERT INTO countries (id, code, name) VALUES (138, 'mt', 'Malta');
INSERT INTO countries (id, code, name) VALUES (139, 'mh', 'Marshall Islands');
INSERT INTO countries (id, code, name) VALUES (140, 'mq', 'Martinique');
INSERT INTO countries (id, code, name) VALUES (141, 'mr', 'Mauritania');
INSERT INTO countries (id, code, name) VALUES (142, 'mu', 'Mauritius');
INSERT INTO countries (id, code, name) VALUES (143, 'yt', 'Mayotte');
INSERT INTO countries (id, code, name) VALUES (144, 'mx', 'Mexico');
INSERT INTO countries (id, code, name) VALUES (145, 'fm', 'Micronesia, Federated States of');
INSERT INTO countries (id, code, name) VALUES (146, 'md', 'Moldova, Republic of');
INSERT INTO countries (id, code, name) VALUES (147, 'mc', 'Monaco');
INSERT INTO countries (id, code, name) VALUES (148, 'mn', 'Mongolia');
INSERT INTO countries (id, code, name) VALUES (149, 'me', 'Montenegro');
INSERT INTO countries (id, code, name) VALUES (150, 'ms', 'Montserrat');
INSERT INTO countries (id, code, name) VALUES (151, 'ma', 'Morocco');
INSERT INTO countries (id, code, name) VALUES (152, 'mz', 'Mozambique');
INSERT INTO countries (id, code, name) VALUES (153, 'mm', 'Myanmar');
INSERT INTO countries (id, code, name) VALUES (154, 'na', 'Namibia');
INSERT INTO countries (id, code, name) VALUES (155, 'nr', 'Nauru');
INSERT INTO countries (id, code, name) VALUES (156, 'np', 'Nepal');
INSERT INTO countries (id, code, name) VALUES (157, 'nl', 'Netherlands');
INSERT INTO countries (id, code, name) VALUES (158, 'nc', 'New Caledonia');
INSERT INTO countries (id, code, name) VALUES (159, 'nz', 'New Zealand');
INSERT INTO countries (id, code, name) VALUES (160, 'ni', 'Nicaragua');
INSERT INTO countries (id, code, name) VALUES (161, 'ne', 'Niger');
INSERT INTO countries (id, code, name) VALUES (162, 'ng', 'Nigeria');
INSERT INTO countries (id, code, name) VALUES (163, 'nu', 'Niue');
INSERT INTO countries (id, code, name) VALUES (164, 'nf', 'Norfolk Island');
INSERT INTO countries (id, code, name) VALUES (165, 'mp', 'Northern Mariana Islands');
INSERT INTO countries (id, code, name) VALUES (166, 'no', 'Norway');
INSERT INTO countries (id, code, name) VALUES (167, 'om', 'Oman');
INSERT INTO countries (id, code, name) VALUES (168, 'pk', 'Pakistan');
INSERT INTO countries (id, code, name) VALUES (169, 'pw', 'Palau');
INSERT INTO countries (id, code, name) VALUES (170, 'ps', 'Palestine, State of');
INSERT INTO countries (id, code, name) VALUES (171, 'pa', 'Panama');
INSERT INTO countries (id, code, name) VALUES (172, 'pg', 'Papua New Guinea');
INSERT INTO countries (id, code, name) VALUES (173, 'py', 'Paraguay');
INSERT INTO countries (id, code, name) VALUES (174, 'pe', 'Peru');
INSERT INTO countries (id, code, name) VALUES (175, 'ph', 'Philippines');
INSERT INTO countries (id, code, name) VALUES (176, 'pn', 'Pitcairn');
INSERT INTO countries (id, code, name) VALUES (177, 'pl', 'Poland');
INSERT INTO countries (id, code, name) VALUES (178, 'pt', 'Portugal');
INSERT INTO countries (id, code, name) VALUES (179, 'pr', 'Puerto Rico');
INSERT INTO countries (id, code, name) VALUES (180, 'qa', 'Qatar');
INSERT INTO countries (id, code, name) VALUES (181, 're', 'Réunion');
INSERT INTO countries (id, code, name) VALUES (182, 'ro', 'Romania');
INSERT INTO countries (id, code, name) VALUES (183, 'ru', 'Russian Federation');
INSERT INTO countries (id, code, name) VALUES (184, 'rw', 'Rwanda');
INSERT INTO countries (id, code, name) VALUES (185, 'bl', 'Saint Barthélemy');
INSERT INTO countries (id, code, name) VALUES (186, 'sh', 'Saint Helena, Ascension and Tristan da Cunha');
INSERT INTO countries (id, code, name) VALUES (187, 'kn', 'Saint Kitts and Nevis');
INSERT INTO countries (id, code, name) VALUES (188, 'lc', 'Saint Lucia');
INSERT INTO countries (id, code, name) VALUES (189, 'mf', 'Saint Martin (French part)');
INSERT INTO countries (id, code, name) VALUES (190, 'pm', 'Saint Pierre and Miquelon');
INSERT INTO countries (id, code, name) VALUES (191, 'vc', 'Saint Vincent and the Grenadines');
INSERT INTO countries (id, code, name) VALUES (192, 'ws', 'Samoa');
INSERT INTO countries (id, code, name) VALUES (193, 'sm', 'San Marino');
INSERT INTO countries (id, code, name) VALUES (194, 'st', 'Sao Tome and Principe');
INSERT INTO countries (id, code, name) VALUES (195, 'sa', 'Saudi Arabia');
INSERT INTO countries (id, code, name) VALUES (196, 'sn', 'Senegal');
INSERT INTO countries (id, code, name) VALUES (197, 'rs', 'Serbia');
INSERT INTO countries (id, code, name) VALUES (198, 'sc', 'Seychelles');
INSERT INTO countries (id, code, name) VALUES (199, 'sl', 'Sierra Leone');
INSERT INTO countries (id, code, name) VALUES (200, 'sg', 'Singapore');
INSERT INTO countries (id, code, name) VALUES (201, 'sx', 'Sint Maarten (Dutch part)');
INSERT INTO countries (id, code, name) VALUES (202, 'sk', 'Slovakia');
INSERT INTO countries (id, code, name) VALUES (203, 'si', 'Slovenia');
INSERT INTO countries (id, code, name) VALUES (204, 'sb', 'Solomon Islands');
INSERT INTO countries (id, code, name) VALUES (205, 'so', 'Somalia');
INSERT INTO countries (id, code, name) VALUES (206, 'za', 'South Africa');
INSERT INTO countries (id, code, name) VALUES (207, 'gs', 'South Georgia and the South Sandwich Islands');
INSERT INTO countries (id, code, name) VALUES (208, 'ss', 'South Sudan');
INSERT INTO countries (id, code, name) VALUES (209, 'es', 'Spain');
INSERT INTO countries (id, code, name) VALUES (210, 'lk', 'Sri Lanka');
INSERT INTO countries (id, code, name) VALUES (211, 'sd', 'Sudan');
INSERT INTO countries (id, code, name) VALUES (212, 'sr', 'Suriname');
INSERT INTO countries (id, code, name) VALUES (213, 'sj', 'Svalbard and Jan Mayen');
INSERT INTO countries (id, code, name) VALUES (214, 'sz', 'Swaziland');
INSERT INTO countries (id, code, name) VALUES (215, 'se', 'Sweden');
INSERT INTO countries (id, code, name) VALUES (216, 'ch', 'Switzerland');
INSERT INTO countries (id, code, name) VALUES (217, 'sy', 'Syrian Arab Republic');
INSERT INTO countries (id, code, name) VALUES (218, 'tw', 'Taiwan, Province of China');
INSERT INTO countries (id, code, name) VALUES (219, 'tj', 'Tajikistan');
INSERT INTO countries (id, code, name) VALUES (220, 'tz', 'Tanzania, United Republic of');
INSERT INTO countries (id, code, name) VALUES (221, 'th', 'Thailand');
INSERT INTO countries (id, code, name) VALUES (222, 'tl', 'Timor-Leste');
INSERT INTO countries (id, code, name) VALUES (223, 'tg', 'Togo');
INSERT INTO countries (id, code, name) VALUES (224, 'tk', 'Tokelau');
INSERT INTO countries (id, code, name) VALUES (225, 'to', 'Tonga');
INSERT INTO countries (id, code, name) VALUES (226, 'tt', 'Trinidad and Tobago');
INSERT INTO countries (id, code, name) VALUES (227, 'tn', 'Tunisia');
INSERT INTO countries (id, code, name) VALUES (228, 'tr', 'Turkey');
INSERT INTO countries (id, code, name) VALUES (229, 'tm', 'Turkmenistan');
INSERT INTO countries (id, code, name) VALUES (230, 'tc', 'Turks and Caicos Islands');
INSERT INTO countries (id, code, name) VALUES (231, 'tv', 'Tuvalu');
INSERT INTO countries (id, code, name) VALUES (232, 'ug', 'Uganda');
INSERT INTO countries (id, code, name) VALUES (233, 'ua', 'Ukraine');
INSERT INTO countries (id, code, name) VALUES (234, 'ae', 'United Arab Emirates');
INSERT INTO countries (id, code, name) VALUES (235, 'gb', 'United Kingdom');
INSERT INTO countries (id, code, name) VALUES (236, 'us', 'United States');
INSERT INTO countries (id, code, name) VALUES (237, 'um', 'United States Minor Outlying Islands');
INSERT INTO countries (id, code, name) VALUES (238, 'uy', 'Uruguay');
INSERT INTO countries (id, code, name) VALUES (239, 'uz', 'Uzbekistan');
INSERT INTO countries (id, code, name) VALUES (240, 'vu', 'Vanuatu');
INSERT INTO countries (id, code, name) VALUES (241, 've', 'Venezuela, Bolivarian Republic of');
INSERT INTO countries (id, code, name) VALUES (242, 'vn', 'Viet Nam');
INSERT INTO countries (id, code, name) VALUES (243, 'vg', 'Virgin Islands, British');
INSERT INTO countries (id, code, name) VALUES (244, 'vi', 'Virgin Islands, U.S.');
INSERT INTO countries (id, code, name) VALUES (245, 'wf', 'Wallis and Futuna');
INSERT INTO countries (id, code, name) VALUES (246, 'eh', 'Western Sahara');
INSERT INTO countries (id, code, name) VALUES (247, 'ye', 'Yemen');
INSERT INTO countries (id, code, name) VALUES (248, 'zm', 'Zambia');
INSERT INTO countries (id, code, name) VALUES (249, 'zw', 'Zimbabwe');